# Generated by Django 3.0.7 on 2020-11-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=264)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('msg', models.CharField(default=None, max_length=200)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reciever', to='dbms.CustomerDetails')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dbms.CustomerDetails')),
            ],
        ),
    ]
